name: Publish To Maven

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.MAVEN_KEY }}") | gpg --batch --import

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "temurin"
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Verify GPG signing works
        run: |
          mvn \
          --no-transfer-progress \
          -Dgpg.keyname=${{ secrets.MAVEN_KEY_ID }} \
          verify gpg:sign
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_KEY_PASSWORD }}

      - name: Publish package
        run: |
          mvn \
          --no-transfer-progress \
          --batch-mode \
          -Dgpg.keyname=${{ secrets.MAVEN_KEY_ID }} \
          clean deploy -P release-sign-artifacts -e
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_KEY_PASSWORD }}
